### ISSUE TITLE
Consider querying username using "cn" instead of "name"

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/nfsv3driver#5]
https://github.com/cloudfoundry-incubator/nfsv3driver/blob/master/id_resolver.go#L48

In all my work with ldap I've always used `cn`.  Not sure if there is any other concrete difference.  Perhaps cn will be more likely to have indexes on it and such?  Anyway, something to consider.

**Comment by julian-hj** [comment]
This is fixed in master.  Look for it in the next release (which should be v0.2.2)

**Comment by youngm** [comment]
Thanks @julian-hj
